CREATE TABLE [dbo].[Base14$] (
    [Nro# PIA]              FLOAT (53)     NULL,
    [ID Usuario]            NVARCHAR (255) NULL,
    [Nombre]                NVARCHAR (255) NULL,
    [1er Apellido]          NVARCHAR (255) NULL,
    [2do Apellido]          NVARCHAR (255) NULL,
    [Fecha Ingreso]         NVARCHAR (255) NULL,
    [Negocio]               NVARCHAR (255) NULL,
    [Area]                  NVARCHAR (255) NULL,
    [Sub-Area]              NVARCHAR (255) NULL,
    [Alcance]               NVARCHAR (255) NULL,
    [País]                  NVARCHAR (255) NULL,
    [Id Usuario Supervisor] NVARCHAR (255) NULL,
    [Supervisor]            NVARCHAR (255) NULL,
    [Nivel]                 NVARCHAR (255) NULL,
    [Cargo]                 NVARCHAR (255) NULL,
    [Tipo Evaluación]       NVARCHAR (255) NULL,
    [Correo Electrónico]    NVARCHAR (255) NULL,
    [Fecha Nacimiento]      NVARCHAR (255) NULL,
    [Sexo]                  NVARCHAR (255) NULL,
    [Roll de Evaluación]    NVARCHAR (255) NULL,
    [Resp_1]                NVARCHAR (MAX) NULL,
    [Resp_2]                NVARCHAR (MAX) NULL,
    [Resp_3]                NVARCHAR (MAX) NULL,
    [Resp_4]                NVARCHAR (MAX) NULL,
    [Resp_5]                NVARCHAR (MAX) NULL,
    [Resp_6]                NVARCHAR (MAX) NULL,
    [Resp_7]                NVARCHAR (MAX) NULL,
    [Resp_8]                NVARCHAR (MAX) NULL,
    [Resp_9]                NVARCHAR (MAX) NULL,
    [Resp_10]               NVARCHAR (MAX) NULL,
    [Resp_11]               NVARCHAR (MAX) NULL,
    [Resp_12]               NVARCHAR (MAX) NULL,
    [Resp_13]               NVARCHAR (MAX) NULL,
    [Resp_14]               NVARCHAR (MAX) NULL,
    [Resp_15]               NVARCHAR (MAX) NULL,
    [Resp_16]               NVARCHAR (MAX) NULL,
    [Resp_17]               NVARCHAR (MAX) NULL,
    [Resp_18]               NVARCHAR (MAX) NULL,
    [Resp_19]               NVARCHAR (MAX) NULL,
    [Resp_20]               NVARCHAR (MAX) NULL,
    [Competencia_1]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_1]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_1]   NVARCHAR (MAX) NULL,
    [Competencia_2]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_2]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_2]   NVARCHAR (MAX) NULL,
    [Competencia_3]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_3]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_3]   NVARCHAR (MAX) NULL,
    [Competencia_4]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_4]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_4]   NVARCHAR (MAX) NULL,
    [Competencia_5]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_5]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_5]   NVARCHAR (MAX) NULL,
    [Competencia_6]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_6]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_6]   NVARCHAR (MAX) NULL,
    [Competencia_7]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_7]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_7]   NVARCHAR (MAX) NULL,
    [Competencia_8]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_8]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_8]   NVARCHAR (MAX) NULL,
    [Competencia_9]         NVARCHAR (MAX) NULL,
    [Competencia_Desc_9]    NVARCHAR (MAX) NULL,
    [Competencia_Nivel_9]   NVARCHAR (MAX) NULL
);

